#include <stdio.h>
#include <ctype.h>
int main()
{
    int choice;
    printf("\n                      ---------WikiChem----------                   \n \n                               (V- 1.0)\n");
    printf("\n1 : Start");
    printf("\n2 : Exit");
    printf("\n\nEnter your choice :> ");
    scanf("%d",&choice);
    switch (choice)
    {
        case 1:
        { char arr[100], ch, c1, c2;
        int i;
        printf("\nSign Of Element:> ");
        while(scanf("%s",arr)==1)
        {
            for(i=0; (ch=toupper(getchar()))!='\n'; i++)
            //arr[i]=ch;
            printf("%c and %c\n",c1,c2);
            if(arr[0]=='H' && arr[1] =='e')
                printf("\n      Full name              > : Helium\n\n      Atomic Number          > : 2\n\n      Mass Number            > : 4.002602\n\n      Electron Configuration > : 1s2\n\n      Period Number          > : 1\n\n      Group Number           > : 18\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='L' && arr[1] =='i')
                printf("\n      Full name              > : Lithium\n\n      Atomic Number          > : 3\n\n      Mass Number            > : 6.941\n\n      Electron Configuration > : 1s2 2s1\n\n      Period Number          > : 2\n\n      Group Number           > : 1\n\n      Oxidation Number       > : 1\n\nSign Of Element:> ");
            else if(arr[0]=='B' && arr[1]=='e')
                printf("\n      Full name              > : Beryllium\n\n      Atomic Number          > : 4\n\n      Mass Number            > : 9.012182\n\n      Electron Configuration > : 1s2 2s2\n\n       Period Number          > : 2\n\n      Group Number           > : 2\n\n      Oxidation Number       > : 2\n\nSign Of Element:> ");
            else if(arr[0]=='N' && arr[1]=='e')
                printf("\n      Full name              > : Neon\n\n      Atomic Number          > : 10\n\n      Mass Number            > : 20.1797\n\n      Electron Configuration > : 1s2 2s2 2p3\n\n      Period Number          > : 2\n\n      Group Number           > : 15\n\n      Oxidation Number       > : -3, 2, 3, 4, 5\n\nSign Of Element:> ");
            else if(arr[0]=='N' && arr[1]=='a')
                printf("\n      Full name              > : Sodium\n\n      Atomic Number          > : 11\n\n      Mass Number            > : 22.989770\n\n      Electron Configuration > : 1s2 2s2 2p6\n\n      Period Number          > : 2\n\n      Group Number           > : 18\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='M' && arr[1]=='g')
                printf("\n      Full name              > : Magnesium\n\n      Atomic Number          > : 12\n\n      Mass Number            > : 24.3050\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2\n\n      Period Number          > : 3\n\n      Group Number           > : 2\n\n      Oxidation Number       > : 2\n\nSign Of Element:> ");
            else if(arr[0]=='A' && arr[1]=='l')
                printf("\n      Full name              > : Aluminium\n\n      Atomic Number          > :13\n\n      Mass Number            >  : 26.981538\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p1\n\n      Period Number          > : 3\n\n      Group Number           > : 13\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='S' && arr[1]=='i')
                printf("\n      Full name              > : Silicon\n\n      Atomic Number          > : 14\n\n      Mass Number            > : 28.0855\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p2\n\n      Period Number          > : 3\n\n      Group Number           > :14\n\n      Oxidation Number       > : 4\n\nSign Of Element:> ");
            else if(arr[0]=='C' && arr[1]=='l')
                printf("\n      Full name              > : Chlorine\n\n      Atomic Number          > : 17\n\n      Mass Number            > : 35.453\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p5\n\n      Period Number          > : 3\n\n      Group Number           > : 17\n\n      Oxidation Number       > : -1, 1, 3, 5, 7\n\nSign Of Element:> ");
            else if(arr[0]=='A' && arr[1]=='r')
                printf("\n      Full name              > : Argon\n\n      Atomic Number          > : 18\n\n      Mass Number            > : 39.948\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6\n\n      Period Number          > : 3\n\n      Group Number           > : 18\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='C' && arr[1]=='a')
                printf("\n      Full name              > : Calcium\n\n      Atomic Number          > : 20\n\n      Mass number            > : 40.078\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 4s2\n\n      Period Number          > : 4\n\n     Group Number           > : 2\n\n      Oxidation Number       > : 2\n\nSign Of Element:> ");
            else if(arr[0]=='S' && arr[1]=='c')
                printf("\n      Full name              > : Scandium\n\n      Atomic Number          > : 21\n\n      Mass Number            > : 44.955910\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d1 4s2\n\n      Period Number          > : 4\n\n      Group Number           > : 3\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='T' && arr[1]=='i')
                printf("\n      Full name              > : Titanium\n\n      Atomic Number          > : 22\n\n      Mass Number            > : 47.867\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d2 4s2\n\n      Period Number          > : 4\n\n      Group Number           > : 4\n\n      Oxidation Number       > : 3, 4\n\nSign Of Element:> ");
            else if(arr[0]=='V')
                printf("\n      Full name              > : Vanadium\n\n      Atomic Number          > : 23\n\n      Mass Number            > : 50.9415\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d3 4s2\n\n      Period Number          > : 4\n\n      Group Number           > : 5\n\n      Oxidation Number       > : 2, 3, 4, 5\n\nSign Of Element:> ");
            else if(arr[0]=='C' && arr[1]=='r')
                printf("\n      Full name              > : Chromium\n\n      Atomic Number          > : 24\n\n      Mass Number            > : 51.9961\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d5 4s1\n\n      Period Number          > : 4\n\n      Group Number           > : 6\n\n      Oxidation Number       > : 2, 3, 6\n\nSign Of Element:> ");
            else if(arr[0]=='M' && arr[1]=='n')
                printf("\n      Full name              > : Manganese\n\n      Atomic Number          > : 25\n\n      Mass Number            > : 54.938049\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d5 4s2\n\n      Period Number          > : 4\n\n      Group Number           > : 7\n\n      Oxidation Number       > : 2, 3, 4, 6, 7\n\nSign Of Element:> ");
            else if(arr[0]=='F' && arr[1]=='e')
                printf("\n      Full name              > : Iron\n\n      Atomic Number          > : 26\n\n      Mass Number            > : 55.845\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d6 4s2\n\n      Period Number          > : 4\n\n      Group Number           > : 8\n\n      Oxidation Number       > : 2, 3, 6\n\nSign Of Element:> ");
            else if(arr[0]=='C' && arr[1]=='o')
                printf("\n      Full name              > : Cobalt\n\n      Atomic Number          > : 27\n\n      Mass Number            > : 58.933200\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d7 4s2\n\n      Period Number          > : 4\n\n      Group Number           > : 9\n\n      Oxidation Number       > : 2, 3\n\nSign Of Element:> ");
            else if(arr[0]=='N' && arr[1]=='i')
                printf("\n      Full name              > : Nickel\n\n      Atomic Number          > : 28\n\n      Mass Number            > : 58.6934\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d8 4s2\n\n      Period Number          > : 4\n\n      Group Number           > : 10\n\n      Oxidation Number       > : 2,3\n\nSign Of Element:> ");
            else if(arr[0]=='C' && arr[1]=='u')
                printf("\n      Full name              > : Copper\n\n      Atomic Number          > : 29\n\n      Mass Number            > : 63.546\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s1\n\n      Period Number          > : 4\n\n      Group Number           > : 11\n\n      Oxidation Number       > : 1, 2\n\nSign Of Element:> ");
            else if(arr[0]=='Z' && arr[1]=='n')
                printf("\n      Full name              > : Zinc\n\n      Atomic Number          > : 30\n\n      Mass Number            > : 65.409\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2\n\n      Period Number          > : 4\n\n      Group Number           > : 12\n\n      Oxidation Number       > : 2\n\nSign Of Element:> ");
            else if(arr[0]=='G' && arr[1]=='a')
                printf("\n      Full name              > : Gallium\n\n      Atomic Number          > : 31\n\n      Mass Number            > : 69.723\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p1\n\n      Period Number          > : 4\n\n      Group Number           > : 13\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='G' && arr[1]=='e')
                printf("\n      Full name              > : Germanium\n\n      Atomic Number          > : 32\n\n      Mass Number            > : 72.64\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p2\n\n      Period Number          > : 4\n\n      Group Number           > : 14\n\n      Oxidation Number       > : 4\n\nSign Of Element:> ");
            else if(arr[0]=='A' && arr[1]=='s')
                printf("\n      Full name              > : Arsenic\n\n      Atomic Number          > : 33\n\n      Mass Number            > : 74.92160\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p3\n\n      Period Number          > : 4\n\n      Group Number           > : 15\n\n      Oxidation Number       > : -3, 3, 5\n\nSign Of Element:> ");
            else if(arr[0]=='S' && arr[1]=='e')
                printf("\n      Full name              > : Selenium\n\n      Atomic Number          > : 34\n\n      Mass Number            > : 78.96\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p4\n\n      Period Number          > : 4\n\n      Group Number           > : 16\n\n      Oxidation Number       > : -2, 4, 6\n\nSign Of Element:> ");
            else if(arr[0]=='B' && arr[1]=='r')
                printf("\n      Full name              > : Bromine\n\n      Atomic Number          > : 35\n\n      Mass Number            > : 79.904\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p5\n\n      Period Number          > : 4\n\n      Group Number           > : 17\n\n      Oxidation Number       > : -1, 1, 3, 5, 7\n\nSign Of Element:> ");
            else if(arr[0]=='K' && arr[1]=='r')
                printf("\n      Full name              > : Krypton\n\n      Atomic Number          > : 36\n\n      Mass Number            > : 83.789\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6\n\n      Period Number          > : 4\n\n      Group Number           > : 18\n\n      Oxidation Number       > : 2, 4\n\nSign Of Element:> ");
            else if(arr[0]=='R' && arr[1]=='b')
                printf("\n      Full name              > : Rubidium\n\n      Atomic Number          > : 37\n\n      Mass Number            > : 85.4678\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 5s1\n\n      Period Number          > : 5\n\n      Group Number           > : 1\n\n      Oxidation Number       > : 1\n\nSign Of Element:> ");
            else if(arr[0]=='S' && arr[1]=='r')
                printf("\n      Full name              > : Strontium\n\n      Atomic Number          > : 38\n\n      Mass Number            > : 87.62\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 5s2\n\n      Period Number          > : 5\n\n      Group Number           > : 2\n\n      Oxidation Number       > : 2\n\nSign Of Element:> ");
            else if(arr[0]=='Z' && arr[1]=='r')
                printf("\n      Full name              > : Zirconium\n\n      Atomic Number          > : 40\n\n      Mass Number            > : 91.224\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d2 5s2\n\n      Period Number          > : 5\n\n      Group Number           > : 4\n\n      Oxidation Number       > : 4\n\nSign Of Element:> ");
            else if(arr[0]=='N' && arr[1]=='b')
                printf("\n      Full name              > : Niobium\n\n      Atomic Number          > : 41\n\n      Mass Number            > : 92.90638\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d4 5s1\n\n      Period Number          > : 5\n\n      Group Number           > : 5\n\n      Oxidation Number       > : 3, 5\n\nSign Of Element:> ");
            else if(arr[0]=='M' && arr[1]=='o')
                printf("\n      Full name              > : Molybdenum\n\n      Atomic Number          > : 42\n\n      Mass Number            > : 95.94\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d5 5s1\n\n      Period Number          > : 5\n\n      Group Number           > : 6\n\n      Oxidation Number       > : 2, 3, 4, 5, 6\n\nSign Of Element:> ");
            else if(arr[0]=='T' && arr[1]=='c')
                printf("\n      Full name              > : Technetium\n\n      Atomic Number          > : 43\n\n      Mass Number            > : 97.9072\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d5 5s2\n\n      Period Number          > : 5\n\n      Group Number           > : 7\n\n      Oxidation Number       > : 7\n\nSign Of Element:> ");
            else if(arr[0]=='R' && arr[1]=='u')
                printf("\n      Full name              > : Ruthenium\n\n      Atomic Number          > : 44\n\n      Mass Number            > : 101.07\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d7 5s1\n\n      Period Number          > : 5\n\n      Group Number           > : 8\n\n      Oxidation Number       > : 3, 4, 8\n\nSign Of Element:> ");
            else if(arr[0]=='R' && arr[1]=='h')
                printf("\n      Full name              > : Rhodium\n\n      Atomic Number          > : 45\n\n      Mass Number            > : 102.90550\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d8 5s1\n\n      Period Number          > : 5\n\n      Group Number           > : 9\n\n      Oxidation Number       > : 1, 2, 3, 4\n\nSign Of Element:> ");
            else if(arr[0]=='P' && arr[1]=='d')
                printf("\n      Full name              > : Palladium\n\n      Atomic Number          > : 46\n\n      Mass Number            > : 106.42\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10\n\n      Period Number          > : 5\n\n      Group Number           > : 10\n\n      Oxidation Number       > : 2, 4\n\nSign Of Element:> ");
            else if(arr[0]=='A' && arr[1]=='g')
                printf("\n      Full name              > : Silver\n\n      Atomic Number          > : 47\n\n      Mass Number            > : 107.8682\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s1\n\n      Period Number          > : 5\n\n      Group Number           > : 11\n\n      Oxidation Number       > : 1, 2\n\nSign Of Element:> ");
            else if(arr[0]=='C' && arr[1]=='d')
                printf("\n      Full name              > : Cadmium\n\n      Atomic Number          > : 48\n\n      Mass Number            > : 121.411\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2\n\n      Period Number          > : 5\n\n      Group Number           > : 12\n\n      Oxidation Number       > : 2\n\nSign Of Element:> ");
            else if(arr[0]=='I' && arr[1]=='n')
                printf("\n      Full name              > : Indium\n\n      Atomic Number          > : 49\n\n      Mass Number            > : 114.818\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p1\n\n      Period Number          > : 5\n\n      Group Number           > : 13\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='S' && arr[1]=='n')
                printf("\n      Full name              > : Tin\n\n      Atomic Number          > : 50\n\n      Mass Number            > : 118.710\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p2\n\n      Period Number          > : 5\n\n      Group Number           > : 14\n\n      Oxidation Number       > : 2, 4\n\nSign Of Element:> ");
            else if(arr[0]=='S' && arr[1]=='b')
                printf("\n      Full name              > : Antimony\n\n      Atomic Number          > : 51\n\n      Mass Number            > : 121.760\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p3\n\n      Period Number          > : 5\n\n      Group Number           > : 15\n\n      Oxidation Number       > : -3, 3, 5\n\nSign Of Element:> ");
            else if(arr[0]=='T' && arr[1]=='e')
                printf("\n      Full name              > : Tellurium\n\n      Atomic Number          > : 52\n\n      Mass Number            > : 127.60\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p4\n\n      Period Number          > : 5\n\n      Group Number           > : 16\n\n      Oxidation Number       > : -2, 4, 6\n\nSign Of Element:> ");
            else if(arr[0]=='X' && arr[1]=='e')
                printf("\n      Full name              > : Xenon\n\n      Atomic Number          > : 54\n\n      Mass Number            > : 131.293\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6\n\n      Period Number          > : 5\n\n      Group Number           > : 18\n\n      Oxidation Number       > : 2, 4, 6\n\nSign Of Element:> ");
            else if(arr[0]=='C' && arr[1]=='s')
                printf("\n      Full name              > : Caesium\n\n      Atomic Number          > : 55\n\n      Mass Number            > : 132.90545\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6                                   6s1\n\n      Period Number          > : 6\n\n      Group Number           > : 1\n\n      Oxidation Number       > : 1\n\nSign Of Element:> ");
            else if(arr[0]=='B' && arr[1]=='a')
                printf("\n      Full name              > : Barium\n\n      Atomic Number          > : 56\n\n      Mass Number            > : 137.327\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6                                   6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 2\n\n      Oxidation Number       > : 2\n\nSign Of Element:> ");
            else if(arr[0]=='L' && arr[1]=='a')
                printf("\n      Full name              > : Lanthanum (Lanthanide Series)\n\n      Atomic Number          > : 57\n\n      Mass Number            > : 138.9055\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6                                   5d1 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 3\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='C' && arr[1]=='e')
                printf("\n      Full name              > : Cerium (Lanthanide Series)\n\n      Atomic Number          > : 58\n\n      Mass Number            > : 140.116\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f1 5s2                                   5p6 5d1 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 4\n\n      Oxidation Number       > : 3, 4\n\nSign Of Element:> ");
            else if(arr[0]=='P' && arr[1]=='r')
                printf("\n      Full name              > : Praseodymium (Lanthanide Series)\n\n      Atomic Number          > : 59\n\n      Mass Number            > : 140.90765\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f3 5s2                                   5p6 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 5\n\n      Oxidation Number       > : 3, 4\n\nSign Of Element:> ");
            else if(arr[0]=='N' && arr[1]=='d')
                printf("\n      Full name              > : Neodymium (Lanthanide Series)\n\n      Atomic Number          > : 60\n\n      Mass Number            > : 144.24\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f4 5s2                                   5p6 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 6\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='P' && arr[1]=='m')
                printf("\n      Full name              > : Promethium (Lanthanide Series)\n\n      Atomic Number          > : 61\n\n      Mass Number            > : 144.9127\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f5 5s2                                   5p6 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 7\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='S' && arr[1]=='m')
                printf("\n      Full name              > : Samarium (Lanthanide Series)\n\n      Atomic Number          > : 62\n\n      Mass Number            > : 150.36\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f6 5s2                                   5p6 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 8\n\n      Oxidation Number       > : 2, 3\n\nSign Of Element:> ");
            else if(arr[0]=='E' && arr[1]=='u')
                printf("\n      Full name              > : Europium (Lanthanide Series)\n\n      Atomic Number          > : 63\n\n      Mass Number            > : 151.964\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f7 5s2                                   5p6 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 9\n\n      Oxidation Number       > : 2, 3\n\nSign Of Element:> ");
            else if(arr[0]=='G' && arr[1]=='d')
                printf("\n      Full name              > : Gadolinium (Lanthanide Series)\n\n      Atomic Number          > : 64\n\n      Mass Number            > : 157.25\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f7 5s2                                   5p6 5d1 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 10\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='T' && arr[1]=='b')
                printf("\n      Full name              > : Terbium (Lanthanide Series)\n\n      Atomic Number          > : 65\n\n      Mass Number            > : 158.92534\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f9 5s2                                   5p6 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 11\n\n      Oxidation Number       > : 3,4\n\nSign Of Element:> ");
            else if(arr[0]=='D' && arr[1]=='y')
                printf("\n      Full name              > : Dysprosium (Lanthanide Series)\n\n      Atomic Number          > : 66\n\n      Mass Number            > : 162.500\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f10 5s2                                  5p6 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 12\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='H' && arr[1]=='o')
                printf("\n      Full name              > : Holmium (Lanthanide Series)\n\n      Atomic Number          > : 67\n\n      Mass Number            > : 164.93032\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f11 5s2                                  5p6 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 13\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='E' && arr[1]=='r')
                printf("\n      Full name              > : Erbium (Lanthanide Series)\n\n      Atomic Number          > : 68\n\n      Mass Number            > : 167.259\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f12 5s2                                  5p6 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 14\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='T' && arr[1]=='m')
                printf("\n      Full name              > : Thulium (Lanthanide Series)\n\n      Atomic Number          > : 69\n\n      Mass Number            > : 168.93421\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f13 5s2                                  5p6 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 15\n\n      Oxidation Number       > : 2, 3\n\nSign Of Element:> ");
            else if(arr[0]=='Y' && arr[1]=='b')
                printf("\n      Full name              > : Ytterbium (Lanthanide Series)\n\n      Atomic Number          > : 70\n\n      Mass Number            > : 173.04\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 16\n\n      Oxidation Number       > : 2, 3\n\nSign Of Element:> ");
            else if(arr[0]=='L' && arr[1]=='u')
                printf("\n      Full name              > : Lutetium (Lanthanide Series)\n\n      Atomic Number          > : 71\n\n      Mass Number            > : 174.967\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d1 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 17\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='H' && arr[1]=='f')
                printf("\n      Full name              > : Hafnium\n\n      Atomic Number          > : 72\n\n      Mass Number            > : 178.49\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d2 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 4\n\n      Oxidation Number       > : 4\n\nSign Of Element:> ");
            else if(arr[0]=='W')
                printf("\n      Full name              > : Tungsten\n\n      Atomic Number          > : 74\n\n      Mass Number            > : 183.84\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d4 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 6\n\n      Oxidation Number       > : 2, 3, 4, 5, 6\n\nSign Of Element:> ");
            else if(arr[0]=='R' && arr[1]=='e')
                printf("\n      Full name              > : Rhenium\n\n      Atomic Number          > : 75\n\n      Mass Number            > : 186.207\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d5 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 7\n\n      Oxidation Number       > : 2, 4, 7\n\nSign Of Element:> ");
            else if(arr[0]=='O' && arr[1]=='s')
                printf("\n      Full name              > : Osmium\n\n      Atomic Number          > : 76\n\n      Mass Number            > : 190.23\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d6 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 8\n\n      Oxidation Number       > : 2, 3, 4, 6, 8\n\nSign Of Element:> ");
            else if(arr[0]=='I' && arr[1]=='r')
                printf("\n      Full name              > : Iridium\n\n      Atomic Number          > : 77\n\n      Mass Number            > : 192.217\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d7 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 9\n\n      Oxidation Number       > : 1, 2, 3, 4, 6\n\nSign Of Element:> ");
            else if(arr[0]=='P' && arr[1]=='t')
                printf("\n      Full name              > : Platinum\n\n      Atomic Number          > : 78\n\n      Mass Number            > : 195.078\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d9 6s1\n\n      Period Number          > : 6\n\n      Group Number           > : 10\n\n      Oxidation Number       > : 2, 4\n\nSign Of Element:> ");
            else if(arr[0]=='A' && arr[1]=='u')
                printf("\n      Full name              > : Gold\n\n      Atomic Number          > : 79\n\n      Mass Number            > : 196.96655\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 6s1\n\n      Period Number          > : 6\n\n      Group Number           > : 11\n\n      Oxidation Number       > : 1, 3\n\nSign Of Element:> ");
            else if(arr[0]=='H' && arr[1]=='g')
                printf("\n      Full name              > : Mercury\n\n      Atomic Number          > : 80\n\n      Mass Number            > : 200.59\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 12\n\n      Oxidation Number       > : 1, 2\n\nSign Of Element:> ");
            else if(arr[0]=='T' && arr[1]=='l')
                printf("\n      Full name              > : Thallium\n\n      Atomic Number          > : 81\n\n      Mass Number            > : 204.3833\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 6s2 6p1\n\n      Period Number          > : 6\n\n      Group Number           > : 13\n\n      Oxidation Number       > : 1, 3\n\nSign Of Element:> ");
            else if(arr[0]=='P' && arr[1]=='b')
                printf("\n      Full name              > : Lead\n\n      Atomic Number          > : 82\n\n      Mass Number            > : 207.2\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 6s2 6p2\n\n      Period Number          > : 6\n\n      Group Number           > : 14\n\n      Oxidation Number       > : 2, 4\n\nSign Of Element:> ");
            else if(arr[0]=='B' && arr[1]=='i')
                printf("\n      Full name              > : Bismuth\n\n      Atomic Number          > : 83\n\n      Mass Number            > : 208.98038\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 6s2 6p3\n\n      Period Number          > : 6\n\n      Group Number           > : 15\n\n      Oxidation Number       > : 3, 5\n\nSign Of Element:> ");
            else if(arr[0]=='P' && arr[1]=='o')
                printf("\n      Full name              > : Polonium\n\n      Atomic Number          > : 84\n\n      Mass Number            > : 208.9824\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 6s2 6p4\n\n      Period Number          > : 6\n\n      Group Number           > : 16\n\n      Oxidation Number       > : 2, 4, 6\n\nSign Of Element:> ");
            else if(arr[0]=='A' && arr[1]=='t')
                printf("\n      Full name              > : Astatine\n\n      Atomic Number          > : 85\n\n      Mass Number            > : 209.9871\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 6s2 6p5\n\n      Period Number          > : 6\n\n      Group Number           > : 17\n\n      Oxidation Number       > : -1, 1, 3, 5, 7\n\nSign Of Element:> ");
            else if(arr[0]=='R' && arr[1]=='n')
                printf("\n      Full name              > : Radon\n\n      Atomic Number          > : 86\n\n      Mass Number            > : 222.0176\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 6s2 6p6\n\n      Period Number          > : 6\n\n      Group Number           > : 18\n\n      Oxidation Number       > : 2\n\nSign Of Element:> ");
            else if(arr[0]=='F' && arr[1]=='r')
                printf("\n      Full name              > : Francium\n\n      Atomic Number          > : 87\n\n      Mass Number            > : 223.0197\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 6s2 6p6 7s1\n\n      Period Number          > : 7\n\n      Group Number           > : 1\n\n      Oxidation Number       > : 1\n\nSign Of Element:> ");
            else if(arr[0]=='R' && arr[1]=='a')
                printf("\n      Full name              > : Radium\n\n      Atomic Number          > : 88\n\n      Mass Number            > : 226.0254\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 6s2 6p6 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 2\n\n      Oxidation Number       > : 2\n\nSign Of Element:> ");
            else if(arr[0]=='A' && arr[1]=='c')
                printf("\n      Full name              > : Actinium (Actinide Series)\n\n      Atomic Number          > : 89\n\n      Mass Number            > : 227.0277\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 6s2 6p6 6d1 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 3\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='T' && arr[1]=='h')
                printf("\n      Full name              > : Thorium (Actinide Series)\n\n      Atomic Number          > : 90\n\n      Mass Number            > : 232.0381\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 6s2 6p6 6d2 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 4\n\n      Oxidation Number       > : 4\n\nSign Of Element:> ");
            else if(arr[0]=='P' && arr[1]=='a')
                printf("\n      Full name              > : Protactinium (Actinide Series)\n\n      Atomic Number          > : 91\n\n      Mass Number            > : 231.03588\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f2 6s2 6p6 6d1 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 5\n\n      Oxidation Number       > : 4, 5\n\nSign Of Element:> ");
            else if(arr[0]=='N' && arr[1]=='p')
                printf("\n      Full name              > : Neptunium (Actinide Series)\n\n      Atomic Number          > : 93\n\n      Mass Number            > : 237.0482\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f4 6s2 6p6 6d1 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 7\n\n      Oxidation Number       > : 3, 4, 5, 6\n\nSign Of Element:> ");
            else if(arr[0]=='P' && arr[1]=='u')
                printf("\n      Full name              > : Plutonium (Actinide Series)\n\n      Atomic Number          > : 94\n\n      Mass Number            > : 244.0642\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f6 6s2 6p6 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 8\n\n      Oxidation Number       > : 3, 4, 5, 6\n\nSign Of Element:> ");
            else if(arr[0]=='A' && arr[1]=='m')
                printf("\n      Full name              > : Americium (Actinide Series)\n\n      Atomic Number          > : 95\n\n      Mass Number            > : 243.0614\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f7 6s2 6p6 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 9\n\n      Oxidation Number       > : 3, 4, 5, 6\n\nSign Of Element:> ");
            else if(arr[0]=='C' && arr[1]=='m')
                printf("\n      Full name              > : Curium (Actinide Series)\n\n      Atomic Number          > : 96\n\n      Mass Number            > : 247.0704\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f7 6s2 6p6 6d1 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 10\n\n      Oxidation Number       > : 3, 4\n\nSign Of Element:> ");
            else if(arr[0]=='B' && arr[1]=='k')
                printf("\n      Full name              > : Berkelium (Actinide Series)\n\n      Atomic Number          > : 97\n\n      Mass Number            > : 247.0703\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f9 6s2 6p6 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 11\n\n      Oxidation Number       > : 3, 4\n\nSign Of Element:> ");
            else if(arr[0]=='C' && arr[1]=='f')
                printf("\n      Full name              > : Californium (Actinide Series)\n\n      Atomic Number          > : 98\n\n      Mass Number            > : 251.0796\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f10 6s2 6p6 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 12\n\n      Oxidation Number       > : 3, 4\n\nSign Of Element:> ");
            else if(arr[0]=='E' && arr[1]=='s')
                printf("\n      Full name              > : Einsteinium (Actinide Series)\n\n      Atomic Number          > : 99\n\n      Mass Number            > : 252.0830\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f11 6s2 6p6 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 13\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='F' && arr[1]=='m')
                printf("\n      Full name              > : Fermium (Actinide Series)\n\n      Atomic Number          > : 100\n\n      Mass Number            > : 257.0951\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f12 6s2 6p6 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 14\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='M' && arr[1]=='d')
                printf("\n      Full name              > : Mendelevium (Actinide Series)\n\n      Atomic Number          > : 101\n\n      Mass Number            > : 258.0984\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f13 6s2 6p6 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 15\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='N' && arr[1]=='o')
                printf("\n      Full name              > : Nobelium (Actinide Series)\n\n      Atomic Number          > : 102\n\n      Mass Number            > : 259.1010\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 16\n\n      Oxidation Number       > : 2, 3\n\nSign Of Element:> ");
            else if(arr[0]=='L' && arr[1]=='r')
                printf("\n      Full name              > : Lawrencium (Actinide Series)\n\n      Atomic Number          > : 103\n\n      Mass Number            > : 262.1097\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 7s2 7p1\n\n      Period Number          > : 7\n\n      Group Number           > : 17\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='R' && arr[1]=='f')
                printf("\n      Full name              > : Rutherfordium\n\n      Atomic Number          > : 104\n\n      Mass Number            > : 261.1088\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d2 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 4\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='D' && arr[1]=='b')
                printf("\n      Full name              > : Dubnium\n\n      Atomic Number          > : 105\n\n      Mass Number            > : 262.1141\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d3 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 5\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='S' && arr[1]=='g')
                printf("\n      Full name              > : Seaborgium\n\n      Atomic Number          > : 106\n\n      Mass Number            > : 266.1219\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d4 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 6\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='B' && arr[1]=='h')
                printf("\n      Full name              > : Bohrium\n\n      Atomic Number          > : 107\n\n      Mass Number            > : 264.12\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d5 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 7\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='H' && arr[1]=='s')
                printf("\n      Full name              > : Hassium\n\n      Atomic Number          > : 108\n\n      Mass Number            > : 277\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d6 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 8\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='M' && arr[1]=='t')
                printf("\n      Full name              > : Meitnerium\n\n      Atomic Number          > : 109\n\n      Mass Number            > : 268.1388\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d7 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 9\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='D' && arr[1]=='s')
                printf("\n      Full name              > : Darmstadtium\n\n      Atomic Number          > : 110\n\n      Mass Number            > : 271\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d8 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 10\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='R' && arr[1]=='g')
                printf("\n      Full name              > : Roentgenium\n\n      Atomic Number          > : 111\n\n      Mass Number            > : 272\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d9 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 11\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='C' && arr[1]=='n')
                printf("\n      Full name              > : Copernicium\n\n      Atomic Number          > : 112\n\n      Mass Number            > : 285\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d10 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 12\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='C')
                printf("\n      Full name              > : Carbon\n\n      Atomic Number          > : 6\n\n      Mass Number            > : 12.0107\n\n      Electron Configuration > : 1s2 2s2 2p2\n\n      Period Number          > : 2\n\n      Group Number           > : 14\n\n      Oxidation Number       > : -4, 2, 4\n\nSign Of Element:> ");
            else if(arr[0]=='S')
                printf("\n      Full name              > : Sulphur\n\n      Atomic Number          > : 16\n\n      Mass Number            > : 32.065\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p4\n\n      Period Number          > : 3\n\n      Group Number           > : 16\n\n      Oxidation Number       > : -2, 2, 4, 6\n\nSign Of Element:> ");
            else if(arr[0]=='F')
                printf("\n      Full name              > : Fluorine\n\n      Atomic Number          > : 9\n\n      Mass Number            > : 18.9984032\n\n      Electron Configuration > : 1s2 2s2 2p5\n\n      Period Number          > : 2\n\n      Group Number           > : 17\n\n      Oxidation Number       > : -1\n\nSign Of Element:> ");
            else if(arr[0]=='N')
                printf("\n      Full name              > : Nitrogen\n\n      Atomic Number          > : 7\n\n      Mass Number            > : 14.0067\n\n      Electron Configuration > : 1s2 2s2 2p6 3s1\n\n      Period Number          > : 3\n\n      Group Number           > : 1\n\n      Oxidation Number       > : 1\n\nSign Of Element:> ");
            else if(arr[0]=='B')
               printf("\n       Full name              > : Boron\n\n      Atomic Number          > : 5\n\n      Mass Number             > : 10.811\n\n      Electron Configuration > : 1s2 2s2 2p1\n\n      Period Number          > : 2\n\n      Group Number           > : 13\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='K')
                printf("\n      Full name              > : Potassium\n\n      Atomic Number          > : 19\n\n      Mass Number            > : 39.0983\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 4s1\n\n      Period Number          > : 4\n\n      Group Number           > : 1\n\n      Oxidation Number       > : 1\n\nSign Of Element:> ");
            else if(arr[0]=='P')
                printf("\n      Full name              > : Phosphorus\n\n      Atomic Number          > : 15\n\n      Mass Number            > : 30.973761\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p3\n\n      Period Number          > : 3\n\n      Group Number           > : 15\n\n      Oxidation Number       > : -3, 3, 5\n\nSign Of Element:> ");
            else if(arr[0]=='H')
                printf("\n      Full name              > : Hydrogen\n\n      Atomic Number          > : 1\n\n      Mass Number            > : 1.00794\n\n      Electron Configuration > : 1s1\n\n      Period Number          > : 1\n\n      Group Number           > : 1\n\n      Oxidation Number       > : -1, 1\n\nSign Of Element:> ");
            else if(arr[0]=='Y')
                printf("\n      Full name              > : Yttrium\n\n      Atomic Number          > : 39\n\n      Mass Number            > : 88.90585\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d1 5s2\n\n      Period Number          > : 5\n\n      Group Number           > : 3\n\n      Oxidation Number       > : 3\n\nSign Of Element:> ");
            else if(arr[0]=='O')
                printf("\n      Full name              > : Oxygen\n\n      Atomic Number          > : 8\n\n      Mass Number            > : 15.9994\n\n      Electron Configuration > : 1s2 2s2 2p4\n\n      Period Number          > : 2\n\n      Group Number           > : 16\n\n      Oxidation Number       > : -2, -1\n\nSign Of Element:> ");
            else if(arr[0]=='I')
                printf("\n      Full name              > : Iodine\n\n      Atomic Number          > : 53\n\n      Mass Number            > : 126.90447\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p5\n\n      Period Number          > : 5\n\n      Group Number           > : 17\n\n      Oxidation Number       > : -1, 1, 3, 5, 7\n\nSign Of Element:> ");
            else if(arr[0]=='T')
                printf("\n      Full name              > : Tantalum\n\n      Atomic Number          > : 73\n\n      Mass Number            > : 180.9479\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d3 6s2\n\n      Period Number          > : 6\n\n      Group Number           > : 5\n\n      Oxidation Number       > : 5\n\nSign Of Element:> ");
            else if(arr[0]=='U' && arr[1]=='u' && arr[2]=='t')
                printf("\n      Full name              > : Ununtrium\n\n      Atomic Number          > : 113\n\n      Mass Number            > : 284\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d10 7s2 7p1\n\n      Period Number          > : 7\n\n      Group Number           > : 13\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='U' && arr[1]=='u' && arr[2]=='q')
                printf("\n      Full name              > : Ununquadium\n\n      Atomic Number          > : 114\n\n      Mass Number            > : 285\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d10 7s2 7p2\n\n      Period Number          > : 7\n\n      Group Number           > : 14\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='U' && arr[1]=='u' && arr[2]=='p')
                printf("\n      Full name              > : Ununpentium\n\n      Atomic Number          > : 115\n\n      Mass Number            > : 288\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d10 7s2 7p3\n\n      Period Number          > : 7\n\n      Group Number           > : 15\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='U' && arr[1]=='u' && arr[2]=='h')
                printf("\n      Full name              > : Ununhexium\n\n      Atomic Number          > : 116\n\n      Mass Number            > : 292\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d10 7s2 7p4\n\n      Period Number          > : 7\n\n      Group Number           > : 16\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='U' && arr[1]=='u' && arr[2]=='s')
                printf("\n      Full name              > : Ununseptium (Not Yet Observed)\n\n      Atomic Number          > : 117\n\n      Mass Number            > : \n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d10 7s2 7p5\n\n      Period Number          > : 7\n\n      Group Number           > : 17\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='U' && arr[1]=='u' && arr[2]=='o')
                printf("\n      Full name              > : Ununoctium (Not Yet Observed)\n\n      Atomic Number          > : 118\n\n      Mass Number            > : \n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f14 6s2 6p6 6d10 7s2 7p6\n\n      Period Number          > : 7\n\n      Group Number           > : 18\n\n      Oxidation Number       > : N/A\n\nSign Of Element:> ");
            else if(arr[0]=='U')
                printf("\n      Full name              > : Uranium\n\n      Atomic Number          > : 92\n\n      Mass Number            > : 238.02891\n\n      Electron Configuration > : 1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2                                  5p6 5d10 5f3 6s2 6p6 6d1 7s2\n\n      Period Number          > : 7\n\n      Group Number           > : 6\n\n      Oxidation Number       > : 3, 4, 5, 6\n\nSign Of Element:> ");
            }
        }
    }
}
